version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.4

resources:
  semver_tags: &semver_tags
    tags:
      # Simplified SemVer regex
      only: /^\d+\.\d+\.\d+$/

workflows:
  main:
    jobs:
      - pack:
          filters:
            <<: *semver_tags
      - test:
          requires:
            - pack
          filters:
            <<: *semver_tags
      - publish-dev:
          requires:
            - test
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
          context: orb-publishing
      - publish:
          requires:
            - test
          filters:
            <<: *semver_tags
            branches:
              ignore: /.*/
          context: orb-publishing

jobs:
  pack:
    executor: cli/default
    steps:
      - checkout
      - run:
          name: "Pack Orb into a single file"
          command: circleci config pack src > orb.yml
      - persist_to_workspace:
          root: ./
          paths:
            - orb.yml
  test:
    executor: cli/default
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: "Validate Orb config"
          command: circleci orb validate orb.yml
  publish-dev:
    description: Publish PR's to dev releases on Orb registry
    executor: cli/default
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: "Publish orb via the CircleCI CLI"
          command: |
            CIRCLE_PR_NUMBER=$(echo $CI_PULL_REQUEST | cut -d/ -f7)
            if [ "x" != "x$CIRCLE_PR_NUMBER" ]; then
              circleci orb publish orb.yml titel-media/gcp-gke@dev-pr-${CIRCLE_PR_NUMBER}
            else
              echo "Skipping dev orb publising as build is not attached to a pull request"
            fi
  publish:
    executor: cli/default
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: "Publish orb via the CircleCI CLI"
          command: circleci orb publish orb.yml titel-media/gcp-gke@${CIRCLE_TAG}
